// src/app/api/auth/login/route.ts

import { NextResponse, NextRequest } from "next/server";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { UAParser } from "ua-parser-js";
import { Temporal } from "temporal-polyfill";
import { db } from "@/prisma/db";
import { authVerify } from "@/lib/auth/verify";
import { or } from "@prisma/orm-postgres/orm-client";

const JWT_SECRET = process.env.JWT_SECRET!;
const SESSION_DAYS = 30;

export interface authToken {
    userId: string;
    sessionId: string;
    email: string;
}

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { email, password, fingerprint } = body;

        // 1. Already logged in?
        const auth = await authVerify({ req: request });
        if (auth.success) {
            return NextResponse.json(
                { success: false, error: "You are already logged in!" },
                { status: 400 }
            );
        }

        // 2. Validate
        if (!email || !password) {
            return NextResponse.json(
                { success: false, error: "Email and password are required" },
                { status: 400 }
            );
        }

        const identifier = email.toLowerCase().trim();

        // 3. Find user
        const user = await db.orm.public.User.where((u: any) =>
            or(u.email.eq(identifier), u.username.eq(identifier))
        ).first();

        if (!user) {
            return NextResponse.json({ success: false, error: "Invalid credentials" }, { status: 401 });
        }

        // 4. Compare password
        const match = await bcrypt.compare(password, user.password);
        if (!match) {
            return NextResponse.json({ success: false, error: "Invalid credentials" }, { status: 401 });
        }

        // 5. Parse device info
        const ua = request.headers.get("user-agent") || "";
        const parsed = new UAParser(ua).getResult();
        const deviceName = parsed.device.model || parsed.device.type || "Desktop";
        const browser = parsed.browser.name
            ? `${parsed.browser.name} ${parsed.browser.version ?? ""}`.trim()
            : null;
        const os = parsed.os.name
            ? `${parsed.os.name} ${parsed.os.version ?? ""}`.trim()
            : null;

        const geo = (request as any).geo;
        const city = geo?.city ?? null;
        const country = geo?.country ?? null;

        // 6. Create session — id auto-generated by cuid(2)
        const expiresAt = Temporal.Now.instant().add({ hours: SESSION_DAYS * 24 });

        const session = await db.orm.public.Session.create({
            userId: user.id,
            expiresAt,
            fingerprint: fingerprint ?? null,
            deviceName,
            browser,
            os,
            city,
            country,
        });

        // 7. Sign JWT
        const token = jwt.sign(
            { userId: user.id, sessionId: session.id, email: user.email },
            JWT_SECRET,
            { expiresIn: `${SESSION_DAYS}d` }
        );

        // 8. Response + cookie
        const response = NextResponse.json({
            success: true,
            message: "Logged in",
            user: {
                id: user.id,
                username: user.username,
                email: user.email,
                world: user.world,
            },
        });

        response.cookies.set("authToken", token, {
            httpOnly: true,
            secure: process.env.NODE_ENV === "production",
            sameSite: "lax",
            maxAge: SESSION_DAYS * 24 * 60 * 60,
            path: "/",
        });

        return response;
    } catch (err) {
        console.error("Login error:", err);
        return NextResponse.json({ success: false, error: "Something went wrong" }, { status: 500 });
    }
}